services:
  app:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    ports:
      - 8000:80
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./code/:/var/www/html