name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shopware_version: ['6.5.4.1', '6.5.5.2', '6.5.6.1', '6.5.7.4', '6.5.8.12', '6.6.0.3', '6.6.1.2', '6.6.2.0', '6.6.3.1', '6.6.4.1']
        locale: ['de-DE', 'en-GB']
        currency: ['EUR']
        include:
          - shopware_version: '6.5.4.1'
            php_version: '8.2'
          - shopware_version: '6.5.5.2'
            php_version: '8.2'
          - shopware_version: '6.5.6.1'
            php_version: '8.2'
          - shopware_version: '6.5.7.4'
            php_version: '8.2'
          - shopware_version: '6.5.8.12'
            php_version: '8.3'
          - shopware_version: '6.6.0.3'
            php_version: '8.3'
          - shopware_version: '6.6.1.2'
            php_version: '8.3'
          - shopware_version: '6.6.2.0'
            php_version: '8.3'
          - shopware_version: '6.6.3.1'
            php_version: '8.3'
          - shopware_version: '6.6.4.1'
            php_version: '8.3'
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/production/Dockerfile
          push: true
          tags: ghcr.io/it-bens/${{ github.repository }}:${{ matrix.shopware_version }}_${{ matrix.locale }}_${{ matrix.currency }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
            SHOPWARE_VERSION=${{ matrix.shopware_version }}
            LOCALE=${{ matrix.locale }}
            CURRENCY=${{ matrix.currency }}
